inherit_from:
  - node_modules/@prettier/plugin-ruby/rubocop.yml

AllCops:
  NewCops: enable

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/RedundantParentheses:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/RedundantInterpolation:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Style/ColonMethodCall:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/IdenticalConditionalBranches:
  Enabled: false

Layout/LineLength:
  Enabled: false