default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("DBNAME_DEV") { "gumtective_development" } %>

test:
  <<: *default
  database: <%= ENV.fetch("DBNAME_TEST") { "gumtective_test" } %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
